### ISSUE TITLE
smali debug

### ISSUE THREAD

**Issue by samogot** [DexPatcher/dexpatcher-gradle#16]
Can you add tasks for generating smali code for debuging using https://github.com/JesusFreke/smali/wiki/smalidea or apktool debug mode for source and/or patched apps

If it possible to debug patched methods as java code and code of source app as smali - it would be ideal

**Comment by Lanchon** [comment]
right now IDEA is able to decompile the source app to non-functional java source. just click deep into the libraries in your project.

i don't use smalidea. actually, i've never used any debugger in any platform at all; for good or bad, i just printf :) so i don't have experience.

i could add smali output (via apktool only) on next release (when there is one!). the output would be on the source project. would this be enough to run smalidea?

what happens in android studio when you debug an apk for which you have no source? doesn't it show the dalvik bytecode being executed somehow? doesn't this work when using dexpatcher-gradle?

what is smalidea anyway? isn't it a gradle plugin to build an APK from smali source and debug through the smali source? then this isn't applicable to dexpatcher. dexpatcher does not go though smali, it patches the dalvik bytecode directly.

**Comment by Lanchon** [comment]
closed due to inactivity
