### ISSUE TITLE
How to delete the dependencies from Source Apk?

### ISSUE THREAD

**Issue by Fenil15** [DexPatcher/dexpatcher-gradle#20]
@Lanchon In patched/build.gradle while importing aar file you have mention -

> Alternatively we could delete the copy brought in by the source
> app using DexPatcher package annotations.
> 

Can you let me know on how to use DexPatcher package annotations?
I have used Dexpatcher Add/Edit Annotations in **java** file but how to use it in **gradle** file I don't know and couldn't find anywhere in documentation

**Comment by Lanchon** [comment]
already replied here:
https://github.com/DexPatcher/dexpatcher-gradle/issues/19#issuecomment-409833429
