### ISSUE TITLE
How to use dexpatcher-gradle?

### ISSUE THREAD

**Issue by wanglinako0** [DexPatcher/dexpatcher-gradle#31]
Hi @Lanchon,

I just checked the dexpatcher-gradle.
But I am not sure how to modify the apk at source code level.

Could you explain how to use the dexpatcher-gradle in detail?
I am using Android Studio.

Thanks

**Comment by surendrajat** [comment]
Check out this [repo](https://github.com/DexPatcher/dexpatcher-gradle-samples) and each folder here is an app being patched. Analyze it and reuse it.

**Comment by Lanchon** [comment]
it's all explained here...
https://dexpatcher.github.io/

really, spoon feeding is not something RE people need.

"this obfuscated bytecode is not properly commented!"
-- no RE expert ever
