### ISSUE TITLE
Android Studio preview layout not render in all layouts in design mode

### ISSUE THREAD

**Issue by lcm92** [DexPatcher/dexpatcher-gradle#35]
This is my demo source code dependency
![ic_source_dependency](https://user-images.githubusercontent.com/16145808/99463835-39070b80-2969-11eb-9e3b-d83c086e2774.png)

and demo patch code dependency
![ic_patch_dependency](https://user-images.githubusercontent.com/16145808/99463754-0fe67b00-2969-11eb-9aa7-3f50cb544d6e.png)

When I try to preview layout in design mode, the view does not render in all layouts that use: **androidx.constraintlayout.widget.ConstraintLayout** give the following error `the following classes could not be instantiated`

I did clean and rebuild project, invalidates caches / restart, close and reopen Android Studio, but did not solve the problem.

![ic_error_view](https://user-images.githubusercontent.com/16145808/99464399-9e0f3100-296a-11eb-8966-f403af56d90a.png)

**Comment by Lanchon** [comment]
sorry i've no idea. maybe it's an AS bug, maybe you are doing something wrong. no way to know.

why are you depending on that stuff in the patch? is it not part of the APK? by default the APK names are imported already.

**Comment by lcm92** [comment]
Have you tried yet? I have tried with a few apps using ConstraintLayout or some other libraries belonging to androidx and their own properties didn't work in Android Preview.
