### ISSUE TITLE
(BuildConfig.java:0): already exists

### ISSUE THREAD

**Issue by oooooooko** [DexPatcher/dexpatcher-gradle#42]
When building, it prompts (BuildConfig.java:0): already exists. The version of dexpatcher-gradle is 2.0.0

![image](https://github.com/DexPatcher/dexpatcher-gradle/assets/48895716/ccd53947-de0c-4ded-98a6-9527c380c1b7)

**Comment by ffdsss** [comment]
It has been solved, just modify the package name of the manifest

**Comment by oooooooko** [comment]
It has been solved, just modify the package name of the manifest
